### PR TITLE
Support DI with array of descendants

### PR DESCRIPTION
**Pull request by elliotize**
Goal: Support Dependency Injections when the argument is an array. The type of the array is used to find all the descendants of that type.

### CODE REVIEW

**Comment by Bonemind** [comment]
Cool, Nice feature :)

If you can add a small description at the bottom of "Usage" in the readme and an example, I'll merge this

EDIT: To clarify, this is more or less implicit behavior which isn't immediately clear, so I think an example is necessary, as well as like 2 lines of explanation

**Comment by elliotize** [comment]
@Bonemind I added the usage. I am making an Domain Event Library Shard. Might name it SyringeEvent seeing as its only dependency is this and I cannot think of a more creative name. I figured you wanted to keep this shard simple and focused on DI.

**Comment by Bonemind** [comment]
Thanks for the update, I'll merge and bump versions later today.

As for your events library, I have nothing against calling it SyringeEvent. However, I suggest Prism because it allows a source to distribute and events across multiple receivers, kind of like like refracting out of a prism. Your choice however, it's your shard after all.

**Comment by elliotize** [comment]
@Bonemind I really like prism however someone liked it already for their game engine https://github.com/neutrinog/prism

**Pull request merged**
